name: Github Action Exercise

on:
  push:
    branches:
      - main  # or any other branch

jobs:
  run-custom-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Generate item via sdkTest.js
        env: 
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: node sdkNewItem.js

      - name: Install CLI and retrieve item details
        env: 
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          node cliInstallAndTest.js
          op --version
      
      - name: Execute additional CLI commands directly in Config file.
        env: 
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          op item list --vault w24doqg47q4bcmqto6wphqn7ye 
