name: Run Script

on:
  push:
    branches:
      - main  # or any other branch

jobs:
  run-custom-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SDK Goals script
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: node ./sdkgoals.js

      - name: test op command
        run: |
         op vault list
